// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import "package:firebase_core/firebase_core.dart" show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC96fYF7hCO0pSCjTb8FJ7qzfLHcTThARY',
    appId: '1:753747249940:web:867d932abb89f7aae75001',
    messagingSenderId: '753747249940',
    projectId: 'flutter-recipe-app-90974',
    authDomain: 'flutter-recipe-app-90974.firebaseapp.com',
    storageBucket: 'flutter-recipe-app-90974.firebasestorage.app',
    measurementId: 'G-BRZXNLL8RG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBKywjylvF-L7vSMT23MK5wrmtKXuqpiE',
    appId: '1:753747249940:android:789a8d2775d9724ce75001',
    messagingSenderId: '753747249940',
    projectId: 'flutter-recipe-app-90974',
    storageBucket: 'flutter-recipe-app-90974.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDf2J64xvvb9Zt6MndZ0ws-8XX3sPkI5AA',
    appId: '1:753747249940:ios:7e8414f647c39e59e75001',
    messagingSenderId: '753747249940',
    projectId: 'flutter-recipe-app-90974',
    storageBucket: 'flutter-recipe-app-90974.firebasestorage.app',
    iosBundleId: 'com.example.recipeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDf2J64xvvb9Zt6MndZ0ws-8XX3sPkI5AA',
    appId: '1:753747249940:ios:7e8414f647c39e59e75001',
    messagingSenderId: '753747249940',
    projectId: 'flutter-recipe-app-90974',
    storageBucket: 'flutter-recipe-app-90974.firebasestorage.app',
    iosBundleId: 'com.example.recipeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC96fYF7hCO0pSCjTb8FJ7qzfLHcTThARY',
    appId: '1:753747249940:web:fa32d92ed17b6c5fe75001',
    messagingSenderId: '753747249940',
    projectId: 'flutter-recipe-app-90974',
    authDomain: 'flutter-recipe-app-90974.firebaseapp.com',
    storageBucket: 'flutter-recipe-app-90974.firebasestorage.app',
    measurementId: 'G-W7N7P3D6Y0',
  );
}
